### ISSUE TITLE
Verification HTTP 400 Error

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#211]
Attempts to verify this contract result in error:
https://explorer.gochain.io/verify?address=0xA7620862540F635342B166206108D7B31C875Dd8
Name: MirrorSC
Code: https://gist.github.com/jmank88/c86d4bd7772ac90954320914f1d60ecc

The interface displays: `ERROR OCCURRED DURING ANTI-BOT CHECKING. PLEASE TRY AGAIN`

The javascript console shows `https://explorer.gochain.io/api/verify` returning `400` and then a null field access on the empty response object.

**Comment by bergauz** [comment]
@jmank88 disabled recaptcha3, will make recaptcha2. Right now getting compile error, checking

**Comment by jmank88** [comment]
Has this been resolved?

**Comment by bergauz** [comment]
it should be fixed by https://github.com/gochain-io/explorer/pull/244

**Comment by jmank88** [comment]
I am still seeing the same behavior. Can anyone reproduce this? The `400` is one problem, but there is a secondary problem with handling the error as well: `Cannot read property 'valid' of null`

**Comment by jmank88** [comment]
In the server logs I see:
```
ERR error while compilation error="solc: exit status 125\ndocker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.\nSee 'docker run --help'.\n"
```
Shouldn't that be a 500 or something? Not a 400?

**Comment by r-gochain** [comment]
Tested on testnet, works

**Comment by jmank88** [comment]
Now I get the error "INVALID CONTRACT NAME", and the same 400 response with a null pointer error in the console.

**Comment by jmank88** [comment]
- [ ] The text above the inputs should explain that 'Contract Name' must match a contract from the source - maybe the error should explain this too
- [ ] When a 400 is returned (invalid contract name, mismatched output, etc.), the `valid` field should not be accessed - this causes a null pointer
![Screenshot from 2019-05-03 11-37-36](https://user-images.githubusercontent.com/1194128/57152017-f0442d80-6d97-11e9-965b-b501405113d4.png)

**Comment by r-gochain** [comment]
LGTM, the contract name is "Mirror"
